server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    username: test
    password: test
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/test?useSSL=false


mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: ["classpath:mapper/**/*.xml"]




#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database: mysql